name: codemon
options:
  bundleIdPrefix: dev.adrian
  deploymentTarget:
    macOS: "13.0"
packages:
  AppUpdater:
    url: https://github.com/s1ntoneli/AppUpdater.git
    branch: main
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    from: 2.2.0
targets:
  codemon:
    type: application
    platform: macOS
    sources:
      - path: codemon
    dependencies:
      - package: AppUpdater
      - package: KeyboardShortcuts
    info:
      path: codemon/Info.plist
      properties:
        LSUIElement: true
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        NSHumanReadableCopyright: ""
    entitlements:
      path: codemon/codemon.entitlements
      properties:
        com.apple.security.app-sandbox: false
        com.apple.security.network.client: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.adrian.codemon
        PRODUCT_NAME: codemon
        MARKETING_VERSION: "1.2.5"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.0"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: true
        GENERATE_INFOPLIST_FILE: false
schemes:
  codemon:
    build:
      targets:
        codemon: all
    run:
      config: Debug
